# Ad ogni push, esegui aggiornaContributori.py per aggiornare la lista di contributors per ogni team.

name: AggiornaWiki

on:
  # "Gollum" Ã¨ innescato da ogni modifica o creazione pagina sulla Wiki
  gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout emergenzeHack/covid19italia
      uses: actions/checkout@v2
      with:
        repository: emergenzeHack/covid19italia
        path: covid19italia

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - working-directory: covid19italia/
      run: |
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.DATA_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        git config remote.origin.pushurl git@github.com:emergenzeHack/covid19italia.git
        cd scripts
        git clone git@github.com:emergenzeHack/covid19italia.wiki.git
        pip install MarkdownPP
        markdown-pp templateWiki.mdpp -o ../wiki.md
        git config --local user.name "ehack-italy"
        git config --local user.email "62019251+ehack-italy@users.noreply.github.com"
        git add ../wiki.md
        git commit -m "Aggiorno wiki" && git push || :
